### ISSUE TITLE
Video not loading

### ISSUE THREAD

**Issue by mswubz** [ivadim/fruitnanny#12]
I have the website working however the video just has a loading circle.
I do not have audio set up at the moment because I do not have a microphone. 
Video and janus is enabled and running

Do I need to have the audio running for the video to also work? 

If I go to the website's console this is the printout messages:

Initializing library
janus.js:390 Library initialized: true
janus.js:417 Using REST API to contact Janus: /janus
janus.js:864 Created session: 7963663776931688
janus.js:1119 Created handle: 8954871135075411
webrtc.js:36 Plugin attached! (janus.plugin.streaming, id=8954871135075411)
janus.js:1274 Synchronous transaction successful (janus.plugin.streaming)
webrtc.js:134 Got a list of available streams
webrtc.js:143 Selected video id #1
janus.js:1604 Creating PeerConnection
janus.js:1612 Preparing local SDP and gathering candidates (trickle=true)
janus.js:1644 Handling Remote Track
janus.js:1651 Adding onended callback to track: MediaStreamTrackcontentHint: ""enabled: trueid: "janusa0"kind: "audio"label: "janusa0"muted: falseonended: ƒ (ev)onmute: nullonunmute: nullreadyState: "live"__proto__: MediaStreamTrack
janus.js:1644 Handling Remote Track
janus.js:1651 Adding onended callback to track: MediaStreamTrackcontentHint: ""enabled: trueid: "janusv0"kind: "video"label: "janusv0"muted: trueonended: ƒ (ev)onmute: nullonunmute: nullreadyState: "live"__proto__: MediaStreamTrack
janus.js:1703 Remote description accepted!
janus.js:2463 Creating answer (iceDone=false)
janus.js:2588 Setting local description
janus.js:1620 End of candidates.

**Comment by mswubz** [comment]
I bought a microphone and the audio is now streaming, but the video still has the spinner.

**Comment by firasdr** [comment]
Hi Jnargu, Do you find any solution for the video streaming, I got the same error then you ?!

**Comment by ivadim** [comment]
Please reopen the issue if you still have the problem
