### ISSUE TITLE
video not charged

### ISSUE THREAD

**Issue by firasdr** [ivadim/fruitnanny#13]
Hi #Ivadim, I use USB camera unlike you ( I've changed the gstreamer pipeline for the video) and unfortunately I don't have the video stream , have you any solution for this issue ? and thank you

**Comment by progware** [comment]
Hi firasdr, 

which browser did you use? Lately there was un update of Chrome Browser, and it stopped working on any Chrome I have (on any device). Try with Mozilla (Windows, MacOS) or Samsung Internet (Android). It worked for a while with Safari on iPhone for me, but it is not anymore

Cheers
Piotr

**Comment by firasdr** [comment]
I test it with chrome and with mozila, what's type of camera did you use ?

**Comment by progware** [comment]
I tried with IR-CUT and official one v2.1. There should be no difference with USB cam. 
Check if you can see video0 in /dev/. 
`ls /dev/vi*`

And check video.service in journalctl maybe you find some answers what is wrong in there

**Comment by firasdr** [comment]
I already checked the usb camera in /dev/video0 and i found it(i ran the
gstreamer pipeline in local and it succesfully worked ) and the video
service is also active when i run the app but when i checked the pipeline i
have error of : negotiation stream not started (-4)
I didn't found this error in any forum ! And i am not expert in gstreamer
This is my situation have you any idea that can help me  and thank you

**Comment by progware** [comment]
I would look into gstreamer specs. Could you paste me your gstreamer cmd? Do you convert the video in any way?

**Comment by firasdr** [comment]
this is  the gstreamer cmd :
gst-launch-1.0 -v -e v4l2src device=/dev/video0 ! queue ! \
    video/x-h264,width=640,height=480,framerate=30/1,profile=baseline ! \
    h264parse ! \
    rtph264pay config-interval=2 pt=96 ! udpsink host=127.0.0.1 port=5004
and this is somes pastes of the application while running ;
And thank you for your cooperation

**Comment by progware** [comment]
1) try using videoconvert in gstreamer (sorry I do not have much time to test it)
2) try calling https:// instead of http://

**Comment by ivadim** [comment]
Please reopen the issue if you still have the problem
