### ISSUE TITLE
libsrtp not found when installing janus

### ISSUE THREAD

**Issue by antranapp** [ivadim/fruitnanny#2]
When running configure for janus, I'm getting the error
    
    No package 'libsrtp' found

I tried to install libsrtp-dev but still have the same issue.

**Comment by antranapp** [comment]
OK, I need to build libsrtp from source

```
wget https://github.com/cisco/libsrtp/archive/v1.6.0.tar.gz
tar xfv v1.6.0.tar.gz
cd libsrtp-1.6.0
./configure --prefix=/usr --enable-openssl
make shared_library && sudo make install

```

**Comment by ivadim** [comment]
Hi @peacemoon , thank you for reporting this. Did this code fix the problem?

**Comment by ivadim** [comment]
I updated the article to include libsrtp installation.

**Comment by antranapp** [comment]
yes, the code fixed my problem. I close the issue. Thanks.

**Comment by onajafi** [comment]
`sudo apt-get install libsrtp2-dev`
Worked for me

**Comment by geo-matheou** [comment]
If you install libsrtp2-dev you may install libsrtcp 2.3 and not 2.2 which may cause the issue described here: https://github.com/meetecho/janus-gateway/issues/2024

This happened to me when I used Ubuntu 20.04.4 LTS
