### ISSUE TITLE
Are you planning to develop an app 

### ISSUE THREAD

**Issue by aalzooke** [ivadim/fruitnanny#6]
Hello, 
I really like your project, but I'm still wondering if you are working on making an app for it ? or if you have any suggestion. 
Thank you

**Comment by ivadim** [comment]
Hi @aalzooke, thank you for your interest in fruitnanny project. 
Unfortunately, I don't have time to work on additional application. I thought about it and for iOS it makes total sense but development requires Apple hardware for development and testing which I don't have.
Any contributions are welcome 👍
